/*
 * SPDX-License-Identifier: AGPL-3.0-only
 * Copyright (c) 2022-2025, daeuniverse Organization <dae@v2raya.org>
 */

// Package control - legacy_api_wrapper.go
// This file provides backward compatibility for the old RouteDialTcp API
package control

import (
	"context"
	"fmt"
	"net/netip"

	"github.com/daeuniverse/dae/common"
	"github.com/daeuniverse/dae/common/consts"
	"github.com/daeuniverse/dae/component/outbound/dialer"
	"github.com/daeuniverse/outbound/netproxy"
)

// RouteDialParam represents the parameters for routing and dialing
// This struct is kept for backward compatibility with the old API
type RouteDialParam struct {
	Outbound    consts.OutboundIndex
	Domain      string
	Mac         [6]uint8
	Dscp        uint8
	ProcessName [16]uint8
	Src         netip.AddrPort
	Dest        netip.AddrPort
	Mark        uint32
}

// RouteDialTcp provides backward compatibility for the old API
// It wraps the new RouteDialOption method to maintain the same interface
func (c *ControlPlane) RouteDialTcp(p *RouteDialParam) (conn netproxy.Conn, err error) {
	// Create a routing result based on the parameters
	// Note: We need to simulate the routing result that would have been
	// generated by the BPF program in the old architecture
	routingResult := &bpfRoutingResult{
		Mark:     p.Mark,
		Must:     0,
		Mac:      p.Mac,
		Outbound: uint8(p.Outbound),
		Pname:    p.ProcessName,
		Pid:      0,
		Dscp:     p.Dscp,
	}

	// Create network type
	networkType := &dialer.NetworkType{
		L4Proto:   consts.L4ProtoStr_TCP,
		IpVersion: consts.IpVersionFromAddr(p.Dest.Addr()),
		IsDns:     false,
	}

	// Create route parameters for the new API
	routeParam := &RouteParam{
		routingResult: routingResult,
		networkType:   networkType,
		Domain:        p.Domain,
		Src:           p.Src,
		Dest:          p.Dest,
	}

	// Get dial option using the new API
	dialOption, err := c.RouteDialOption(routeParam)
	if err != nil {
		return nil, fmt.Errorf("failed to get dial option: %w", err)
	}

	// Log the dial operation (matching the old behavior)
	LogDial(p.Src, p.Dest, p.Domain, dialOption, networkType, routingResult)

	// Perform the actual dial
	ctx, cancel := context.WithTimeout(context.TODO(), consts.DefaultDialTimeout)
	defer cancel()
	
	conn, err = dialOption.Dialer.DialContext(ctx, common.MagicNetwork("tcp", dialOption.Mark), dialOption.DialTarget)
	if err != nil {
		return nil, fmt.Errorf("failed to dial %v: %w", p.Dest, err)
	}

	return conn, nil
}

// Note: RelayTCP function is already available in the new implementation
// and should be compatible with the old API, so we don't need to redefine it.
// The WriteCloser interface is also already defined in utils.go.
